name: merchant_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Local storage 
  shared_preferences: ^2.0.8
  # Value equality
  equatable: ^2.0.3
  # State provider
  provider: ^6.0.1
  intl: ^0.17.0
  # Load csv
  csv: ^5.0.1
  # Functional programming
  dartz: ^0.10.0
  # Automate dependency injection
  injectable: ^1.5.0
  # Service locator 
  get_it: ^7.2.0
  # Network calls
  dio: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  injectable_generator:

flutter:

  uses-material-design: true